### ISSUE TITLE
Can not disabled for the CLI

### ISSUE THREAD

**Issue by stevenjlho** [geerlingguy/ansible-role-php-xdebug#34]
I find that this role not use `php_xdebug_cli_enable` anymore, but document still explain the usage of `php_xdebug_cli_enable`. It confused me.

**Comment by alexdesignworks** [comment]
Regression introduced in https://github.com/geerlingguy/ansible-role-php-xdebug/commit/ae8274ac7de60b8aaaf30af397f568dcc9f7b2ce

This is very important issue as `composer` updates are extremely slow.

**Comment by geerlingguy** [comment]
Hmm... you're quite correct. The variable should be added to the config file, as copied here:

https://github.com/geerlingguy/ansible-role-php-xdebug/blob/master/tasks/configure.yml

**Comment by geerlingguy** [comment]
Also, as an aside: if you use a VM for your dev purposes, you can still run PHP outside the VM on your host without Xdebug enabled so you can run composer commands in that environment. Side benefit is that disk access is slightly faster too, so installs/updates are often a little faster.

**Comment by thom8** [comment]
@alexdesignworks in beetbox you can use a custom task -->

```
/.beetbox/tasks/post/php-xdebug.yml
---
- name: disable xdebug for PHP CLI.
  file:
    src: "/etc/php/{{ php_version }}/cli/conf.d/{{ php_xdebug_config_filename }}"
    state: absent
```

The only issue is that each provision will create and then remove the xdebug conf file.

**Comment by alexdesignworks** [comment]
Workaround

```
---
# Enabling/disabling CLI XDebug until upstream issue is fixed.
# @see https://github.com/geerlingguy/ansible-role-php-xdebug/issues/34
- name: Setup variables
  set_fact:
    php_xdebug_config_filename: 20-xdebug.ini

- name: Check state of Xdebug cli file.
  stat:
    path:  "/etc/php/{{ php_version }}/cli/conf.d/{{ php_xdebug_config_filename }}"
  register: php_xdebug_config_filename_state

- name: Disable XDebug for PHP CLI.
  command: mv "/etc/php/{{ php_version }}/cli/conf.d/{{ php_xdebug_config_filename }}" "/etc/php/{{ php_version }}/cli/conf.d/{{ php_xdebug_config_filename }}.bak"
  become: true
  when: not php_xdebug_cli_enable and php_xdebug_config_filename_state.stat.exists == True

- name: Enabled XDebug for PHP CLI.
  command: mv "/etc/php/{{ php_version }}/cli/conf.d/{{ php_xdebug_config_filename }}.bak" "/etc/php/{{ php_version }}/cli/conf.d/{{ php_xdebug_config_filename }}"
  become: true
  when: php_xdebug_cli_enable and php_xdebug_config_filename_state.stat.exists == False
```
