### ISSUE TITLE
Successful Xdebug install marked as failed by Ansible

### ISSUE THREAD

**Issue by wizonesolutions** [geerlingguy/ansible-role-php-xdebug#4]
I'm on CentOS 6.6.

Role configuration:

````yaml
php_xdebug_remote_enable: true
php_xdebug_remote_connect_back: true
php_debug_idekey: cmsbox.xdebug: cmsbox.xdebug
php_xdebug_version: 2.2.6
````
