### ISSUE TITLE
The requested handler 'restart webserver' was not found

### ISSUE THREAD

**Issue by rvanbaalen** [geerlingguy/ansible-role-php-xdebug#48]
I'm running the playbook with the following config:

vars/xdebug.yml:
```
php_xdebug_version: 2.2.5

php_xdebug_coverage_enable: 1
php_xdebug_default_enable: 1
php_xdebug_cli_enable: 1

php_xdebug_remote_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_host: 10.0.2.15
php_xdebug_remote_port: "9000"
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_remote_autostart: "false"

php_xdebug_max_nesting_level: 256

php_xdebug_idekey: "PHPSTORM"
```

But I keep getting the `The requested handler 'restart webserver' was not found` error. 

(Part of) the playbook:
```
- hosts: webdev
  become: yes
  user: vagrant
  vars_files:
  - vars/xdebug.yml
  - vars/apache-dev.yml
  roles:
  - { role: geerlingguy.apache }
  - { role: geerlingguy.php-xdebug }
```

How can this issue be fixed?

**Comment by rvanbaalen** [comment]
I think [this line](https://github.com/geerlingguy/ansible-role-php-xdebug/blob/master/tasks/main.yml#L57) should be changed to a configurable webserver name.

In my case, I'm using Apache which requires it to be `restart apache` instead of `restart webserver`

Or, should the apache role be updated and listen on `restart webserver` for a more generic approach?

**Comment by geerlingguy** [comment]
@rvanbaalen - Ah, I think you ran into a soft dependency on the `geerlingguy.php` role. It defines the `restart webserver` handler, and when I originally built this role, I had a hard dependency on the `geerlingguy.php` role because of it!

See: https://github.com/geerlingguy/ansible-role-php/blob/master/handlers/main.yml#L2-L7

I'm not sure what the best solution would be... One, I could just drop the `notify`, or I could add a handler in this role maybe, and default to not running it?

**Comment by rvanbaalen** [comment]
Interesting! Because I split up my playbook like so:

```
- hosts: web
  roles:
  - { role: geerlingguy.apache }
  - { role: geerlingguy.php }

- hosts: webdev
  roles:
  - { role: geerlingguy.apache }
  - { role: geerlingguy.php-xdebug }
```

That way, the main server config is done in `web` and development specific config in `webdev`.
This also introduces the php role dependency issue. Perhaps I should basically add it to the `webdev` group and it would be fixed.

You already notify users about the php role dependency so I would say there is no need to change anything on your end.
